---
name: linting

on: [push, pull_request]

env:
  TEMPLATE_REPOSITORY: 'T-Systems-MMS/terraform-template'

jobs:
  call-linting:
    if: github.repository != '$TEMPLATE_REPOSITORY'
    uses: T-Systems-MMS/.github/.github/workflows/terraform_linting.yml@main
