---
name: release

on:
  push:
    branches:
      - master
      - main

jobs:
  call-release:
    if: github.repository != 'T-Systems-MMS/terraform-template'
    uses: T-Systems-MMS/.github/.github/workflows/terraform_release.yml@main
