---
name: release

on:
  push:
    branches:
      - master
      - main
env:
  TEMPLATE_REPOSITORY: T-Systems-MMS/terraform-template

jobs:
  call-release:
    if: github.repository != '$TEMPLATE_REPOSITORY'
    uses: T-Systems-MMS/.github/.github/workflows/terraform_release.yml@main
    with:
      readme: terraform
      files: README.md
